### ISSUE TITLE
Link migration error message to our support site

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#31]
The error states to contact support but we don’t have a way to contact support. Can we link the “Contact us” text to [wordpress.com/help](http://wordpress.com/help).

![CleanShot 2024-09-06 at 15 09 49](https://github.com/user-attachments/assets/f3f78ef3-79e2-4e97-8e28-565e0ca3d2ea)

**Comment by markbiek** [comment]
Fixed by https://github.com/blogvault/wpcom-migration/pull/36

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, this is still pending, can you please have another look?

**Comment by markbiek** [comment]
@bv-shivamsharma What's the best way to verify this? Is there a way I can simulate a failure?

**Comment by bv-shivamsharma** [comment]
Please deactivate the destination site wpcom-migration plugin after copying the key and then hit the 'Start Migration' button

**Comment by markbiek** [comment]
I'm still not seeing "contact support" as a link.

![image](https://github.com/user-attachments/assets/e5ce720c-fb2e-417f-a7b5-671513fd2411)

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, sorry for the confusion, I meant that this issue is still not fixed yet, I'm yet to deploy a fix.

**Comment by markbiek** [comment]
> Hi @markbiek, sorry for the confusion, I meant that this issue is still not fixed yet, I'm yet to deploy a fix.

Ah, that makes sense. Thanks for clarifying! Just let me know when it's ready to re-test.

**Comment by sixhours** [comment]
The text and link are not there in the latest version of the plugin: 
<img width="475" alt="Screenshot 2024-09-12 at 8 59 01 AM" src="https://github.com/user-attachments/assets/ec061e87-cf72-4bdd-af3d-3ab8cd61e678">

**Comment by bv-shivamsharma** [comment]
Hi @sixhours, we have many error messages and only a handful have 'contact support' in them. I have only replaced those error messages with the 'contact us' link.

Would you like the 'contact us' link in each error message?

Update - I can append the following text to the error message 'Contact us if you're still having trouble.' if the message doesn't contain the 'contact support' substring. Something like this

![image](https://github.com/user-attachments/assets/74af875e-aa5e-438c-b745-f18e7bb34b1c)

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, @sixhours I have gotten this deployed, let me know if there's any change in the text or link you want me to change and I'll get that fixed in the next deployment.

**Comment by sixhours** [comment]
I see it now, thank you!

<img width="474" alt="Screenshot 2024-09-16 at 11 45 32 AM" src="https://github.com/user-attachments/assets/ef82aa95-3f28-4445-9bbe-92b2c0a3642e">
