### ISSUE TITLE
Cancel migration modal doesn't match the design

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#39]
Current:
![image](https://github.com/user-attachments/assets/45c54977-b6cb-41bd-aee0-21d4e4b54d4b)

Design:
Please note that the static pages we provided include important mobile styles for this modal.
![image](https://github.com/user-attachments/assets/c6aa2e23-3f18-4d86-be9a-f0117a71d133)

**Comment by sixhours** [comment]
Confirmed fixed in https://github.com/blogvault/wpcom-migration/pull/46
