### ISSUE TITLE
Clean up copy on the cancellation page and migration progress page

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#40]
To clean up the appearance of the destination site URL, can we remove the https:// or http:// from the source URL on the cancellation page.

Current
![image](https://github.com/user-attachments/assets/a0971e3d-5427-4490-8bc0-b8aaeb43974f)

Design
![image](https://github.com/user-attachments/assets/cd406b6c-9cbf-4cbf-a531-0f1e9ffea462)
![image](https://github.com/user-attachments/assets/9fc27939-51d9-4d35-8296-05c625d2383d)

**Comment by sixhours** [comment]
Confirmed fixed in https://github.com/blogvault/wpcom-migration/pull/46
