### ISSUE TITLE
Display different loading screen when the first BlogVault page loads

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#41]
When the blogvault app loads, we’re showing this loading screen? Can this be replaced with a WordPress.com loading screen? If so, we can provide a design.

![image](https://github.com/user-attachments/assets/9718dc72-5b11-48e8-941e-66abcd6a2037)

**Comment by markbiek** [comment]
@fditrapani FYI, so you'll get notifications if we need a design for this.

**Comment by fditrapani** [comment]
Thanks Mark! To make this a little more tangible, here's what we use in our product now:

![image](https://github.com/user-attachments/assets/fa6de35b-e6eb-4583-ae70-2c21589dd474)

**Comment by sixhours** [comment]
Confirmed fixed in #46
