### ISSUE TITLE
Spacing tweaks to the credentials form

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#42]
The spacing at the bottom of the credential box feels a tad bit tight. Can we update the bottom padding to 16px so it goes from this:

![image](https://github.com/user-attachments/assets/c57770de-855f-4147-9f42-78da29910984)

To this:
![image](https://github.com/user-attachments/assets/18d1e5e9-6cfb-4925-a6fa-beeb598279da)

**Comment by sixhours** [comment]
Confirmed fixed in #46
