### ISSUE TITLE
Tweak border and round corners on the migration key box

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#43]
The round corners on the bottom right and left of the Migration key field create a weird tension between the field and the highlight below it:

Current
![image](https://github.com/user-attachments/assets/b3b4abaa-6ea6-4aac-80e7-e11faeb3400a)

Design
![image](https://github.com/user-attachments/assets/96f485d0-860e-4e66-b238-04741327fbd5)

**Comment by sixhours** [comment]
Confirmed fixed in #46
