### ISSUE TITLE
Advanced option checkboxes have a gray border around them

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#44]
Current
![image](https://github.com/user-attachments/assets/21a492db-bea9-4cda-904f-fe619f9e1662)

Can we update the border colour when the box is checked so it matches the solid blue:

![image](https://github.com/user-attachments/assets/86619314-c6fe-4868-a991-77c2ad036c1f)

The border should be gray when the box is unchecked.

**Comment by sixhours** [comment]
Confirmed fixed in #46
