### ISSUE TITLE
Update plugin name on plugin page

### ISSUE THREAD

**Issue by fditrapani** [blogvault/wpcom-migration#47]
After you install the plugin, the plugin name on the plugin page is `WordPress.com Migration`. Can we update it to `Migrate to WordPress.com` like everywhere else?

![image](https://github.com/user-attachments/assets/109d2007-0aeb-4849-8ff2-a43db68f9ddc)

**Comment by sixhours** [comment]
Fixed in https://github.com/blogvault/wpcom-migration/pull/53
