### ISSUE TITLE
Open all BlogVault links in a new window

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#50]
Can the Blogvault links open in a new tab? This way, by the end of the migration, you’ll have the source site in one tab and the destination site in another tab, which improves efficiency when spot checking between the two sites.

**Comment by bv-shivamsharma** [comment]
Hi @markbiek 

This is feasible, however, upon doing so, the 'Restart Migration' button will not have much significance on the 'cancel' as well as the 'fail' screen, as it just re-routes the user back to the admin page.

Also, we do not store the admin_url of the source site on our end and mainly use the browser's history to redirect the user back.

![image](https://github.com/user-attachments/assets/05f956d5-88b8-4196-9d1c-daf86c35fa60)

If you still wish to have the 'Restart Migration' button then I'll make the changes accordingly, please let me know

**Comment by bv-shivamsharma** [comment]
One more thing, given the wp-admin page will still be opened on one tab, the user might not get confused and copy the source site migration key onto the form.

![image](https://github.com/user-attachments/assets/2fb87d60-5fe8-485c-b541-6e85a2077c3f)

**Comment by markbiek** [comment]
We may be talking about different things here. I've contacted the user to get more details.

**Comment by sixhours** [comment]
The TOC and Privacy Policy links open in a new tab now!
