### ISSUE TITLE
Jeckpack CSS overriding body tag background color.

### ISSUE THREAD

**Issue by bv-shivamsharma** [blogvault/wpcom-migration#52]
I noticed in the WordPress.com websites that Jectpack's CSS is overriding the body's background color.

Website URL - https://toolsc4327e5d175.wpcomstaging.com
CSS source URL - https://toolsc4327e5d175.wpcomstaging.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-masterbar/dist/admin-color-schemes/colors/classic-dark/colors.css?ver=6.6.2

![image](https://github.com/user-attachments/assets/bc5cd1e7-9440-4f42-9bf3-ac25b6332bbb)

Here are some screenshots.

![image](https://github.com/user-attachments/assets/7d2f594c-cb18-4c54-ab47-9501e84aee4a)

![image](https://github.com/user-attachments/assets/c4c97aa3-2310-4ee6-a09b-5d221df9950b)

![image](https://github.com/user-attachments/assets/5cb6b52d-075f-4e93-a68e-a0c12817ae9c)

@markbiek Can you please confirm if this issue is reproducible at your end?

**Comment by markbiek** [comment]
I can't reproduce this one. On all of my test sites, the background is correctly set to `white`.
