### ISSUE TITLE
Update progress window text to make sure it's clear the user can close the window

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#54]
Let's update the copy to 

> Watch the progress or take a break — your migration will not be disrupted if you close this window. We'll reach out to you at...

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, this has been fixed as well.

**Comment by sixhours** [comment]
<img width="703" alt="Screenshot 2024-09-16 at 11 47 18 AM" src="https://github.com/user-attachments/assets/539baf2f-13e1-4052-9304-454c64c407f3">
 Looks good!
