### ISSUE TITLE
Detect errors on the site when migration is done

### ISSUE THREAD

**Issue by markbiek** [blogvault/wpcom-migration#55]
**This more of a question/exploration, not something that needs to be implemented yet.**

Would it be possible for the migration process to detect critical errors on the destination site? It could display a message to the user like this:

> Your migration was a success, but your migrated site is encountering a critical error. It happens! Contact Support to get help fixing those up.

**Comment by bv-shivamsharma** [comment]
@markbiek Thank you for sharing the feedback, I'll share these requirements with the team and will get back to you.

**Comment by bv-shivamsharma** [comment]
Hi @markbiek

If the website encounters a critical error, this message will be shown on the migration completion page.

![image](https://github.com/user-attachments/assets/9adfa13d-2116-4ea4-9caf-c6ab6fa0ead3)

![image](https://github.com/user-attachments/assets/1f92aedb-838f-458c-8458-cf411e04d356)

**Comment by markbiek** [comment]
Hi @bv-shivamsharma

Is it possible to customize that at all? If possible, the messaging we used above would be great

> Your migration was a success, but your migrated site is encountering a critical error. It happens! Contact Support to get help fixing those up.

We'd also like to have "Contact Support" link to the same support contact we listed on other screens.

@fditrapani Do you have any additional feedback here?

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, no worries, will get the changes deployed.

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, the changes have been deployed. Can you please have a look?

**Comment by markbiek** [comment]
I'm testing this now but I think it will be good. Apologies because I misunderstood your original comment and didn't realize the second screenshot was showing exactly what we want!

**Comment by bv-shivamsharma** [comment]
Hi @markbiek, no worries. Please let me know if you wish to get any changes deployed after you're done with the testing. I'll be more than happy to get those deployed at the earliest.

**Comment by markbiek** [comment]
I'm having trouble activating this.

I have a migrated site that's in an critical error state (https://markbiek344.wpcomstaging.com/) but the migration status page isn't showing the error (https://migrate.blogvault.net/migration/292c150a8180502ce03bbf1a3b609796).

**Comment by bv-shivamsharma** [comment]
I checked the logs and it looks like there was a modification on _./wp-content/plugins/index.php_ to replicate the critical error, however, after migrating the files our system runs a full check to check on the missing or incomplete files, and given, the file _./wp-content/plugins/index.php_ was modified our system replaced the modified file and got a 200 response code upon destination site health check.

Could you please share the error logs of your website so I can debug this further? I need to know why the critical error is still there on your website.

Update - You could replicate the critical error by adding this line at the end of your wp-config.php file
```require_once('non_existent_file.php');```

**Comment by markbiek** [comment]
That site is currently running a small plugin that throws a critical error.

**Comment by bv-shivamsharma** [comment]
@markbiek Can we close this issue?

**Comment by markbiek** [comment]
Yup, I think we're good!
