### ISSUE TITLE
Sidebar logo not visible when using "Light" color scheme

### ISSUE THREAD

**Issue by m1r0** [blogvault/wpcom-migration#56]
Can the logo have a darker color when the "Light" color scheme is selected? Maybe this could be improved on other color schemes as well?

![image](https://github.com/user-attachments/assets/53f961d3-764d-47d1-935a-d686f487b09f)

### Steps to Reproduce

* Go to the `/wp-admin/profile.php`.
* Change the color scheme to "Light".
* Check the plugin logo in the admin sidebar.

**Comment by bv-shivamsharma** [comment]
@m1r0 For the icon to adapt to the current color scheme we'll need to use the dash icons.
Can we replace the current menu image with this https://developer.wordpress.org/resource/dashicons/#wordpress-alt?

Let me know if there's any other alternative.

**Comment by m1r0** [comment]
Sounds good. 👍 They look the same to me. 🙂 

cc @sixhours

**Comment by sixhours** [comment]
@bv-shivamsharma Yep, looks good!

**Comment by bv-shivamsharma** [comment]
@m1r0 Can we please close this issue?
