### ISSUE TITLE
Only show migration key on WordPress.com sites

### ISSUE THREAD

**Issue by sixhours** [blogvault/wpcom-migration#58]
In hopes of avoiding confusion, can we only show the migration key on WordPress.com sites?

We have a global constant `IS_WPCOM` that should work for these purposes:

```
if ( is_defined( 'IS_WPCOM' ) && IS_WPCOM ) {
   //show migration key field
}
```

Please let us know if you have any questions. Thank you!

**Comment by bv-shivamsharma** [comment]
@sixhours We'll plan and complete all the open issues in the next plugin deployment.

**Comment by sixhours** [comment]
@bv-shivamsharma Thank you! Do you have a timeline for that deployment?

**Comment by bv-shivamsharma** [comment]
@sixhours We'll deploy the plugin latest by Tuesday :)

**Comment by bv-shivamsharma** [comment]
Hi @sixhours, we are using the following site for testing https://toolsc4327e5d17.wpcomstaging.com. Unfortunately, the constant IS_WPCOM is not defined.

Here's the piece of code we are using.

```
<?php if (defined( 'IS_WPCOM' ) && IS_WPCOM ) : ?>
  <div class="wpcom-migration-key-section">
	  <h3>Migration in progress?</h3>
	  <p>Grab your key here.</p>
  
	  <div class="wpcom-migration-input-group">
		  <label for="wpcom-migration-email">Migration Key</label>
		  <div class="wpcom-migration-key-input-wrapper">
			  <div class="wpcom-migration-key-input">
				  <input type="password" id="wpcom-migration-key" value="<?php echo esc_attr( $this->bvinfo->getConnectionKey() ); ?>" readonly>
				  <span id="wpcom-toggle-key-visibility" class="dashicons dashicons-hidden"></span>
			  </div>
			  <button type="button" id="wpcom-copy-key" class="secondary" onclick="copyToClipboard()">Copy Key</button>
		  </div>
	  </div>
  </div>
<?php endif; ?>
```

Is this because we're using a wpcomstaging domain? Let us know if we're doing something wrong.

**Comment by sixhours** [comment]
@bv-shivamsharma Hmm, in my tests it was defined on my *.wpcomstaging.com test site, but I'll check and see if there's a better method!

**Comment by sixhours** [comment]
@bv-shivamsharma Let's give this a try instead. This is specific to sites that run on our Atomic infrastructure, ie. sites with `*.wpcomstaging.com` URLs:

```
if ( defined( 'IS_ATOMIC' ) && IS_ATOMIC && defined( 'ATOMIC_CLIENT_ID' )  && '2' === ATOMIC_CLIENT_ID ) {
  // Show the migration key.
}
```

**Comment by bv-shivamsharma** [comment]
@sixhours This has been fixed, can you please close the issue?

**Comment by sixhours** [comment]
Confirmed this was fixed.
