### ISSUE TITLE
Ensure users cannot migrate a site into itself

### ISSUE THREAD

**Issue by sixhours** [blogvault/wpcom-migration#61]
We discussed this already via email but I wanted to create an issue to have a centralized place to track it.

It would be ideal if users could not migrate a site to itself. We'd like to add some kind of validation to prevent this from happening.

**Comment by bv-atulya** [comment]
Hi @sixhours ,
We've implemented a fix to address this. If users attempt to migrate a site to itself, they’ll receive a clear error message to prevent the action. This update should be deployed within the next few days.

**Comment by bv-atulya** [comment]
We’ve identified some complexities with the current fix. We are reviewing them to ensure a comprehensive solution. This additional work may extend the timeline for deploying the update to production.

**Comment by sixhours** [comment]
@bv-atulya Thank you for the heads-up! Please keep us posted on the updated timeline.

**Comment by sixhours** [comment]
Hello! Just checking in. Do you have an updated timeline on the release for this fix?

**Comment by bv-shivamsharma** [comment]
Hi @sixhours, our team is working on the latest fix and we'll deploy the same within a couple of days.
I'll let you know as soon as we deploy.

**Comment by bv-shivamsharma** [comment]
Hi @sixhours, the fix has been deployed.
![image](https://github.com/user-attachments/assets/67ac1e1c-14d6-4264-ab33-6a73553aa291)

**Comment by sixhours** [comment]
Looks great, thank you!
