### ISSUE TITLE
Select all custom database tables and files/folders by default

### ISSUE THREAD

**Issue by sixhours** [blogvault/wpcom-migration#62]
Hello there! We've had a request from our support staff to ensure the plugin selects all custom data tables and folders under the Advanced options _by default_. Users who need these often don't realize they need to look there, so some migrations come across without any custom tables or files.

Please let us know if you need additional information from us to make this happen. Thanks!

**Comment by bv-ritesh** [comment]
Hi

Currently, our system does not migrate custom tables and folders by default. Over the years, and after performing over a million migrations, we've learned that including custom tables and folders often leads to issues. Here are a few examples:

A WordPress site nested within another WordPress site.
- Folders created by caching plugins.
- Folders containing logs.
- Database tables that are present but unused by the site.
- These and similar cases frequently cause problems on migrated sites.

As a result, migrating custom tables and folders by default is not feasible on our end. 


If you’ve noticed any important tables or folders being skipped, please share the details with us. We’ll review them and address the situation as needed.

**Comment by sixhours** [comment]
> If you’ve noticed any important tables or folders being skipped, please share the details with us. We’ll review them and address the situation as needed.

We haven't noticed anything important being skipped, this was a request based on user behavior on our end, but we'll work around it by updating our documentation. Thank you for the insights!
